plugins {
	id 'org.springframework.boot' version "${springBootVersion}" apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

subprojects {
	apply plugin: 'java'

	group = 'org.springaicommunity'
	version = providers.gradleProperty('inspectorVersion').get()

	repositories {
		mavenCentral()
	}

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	tasks.withType(JavaCompile).configureEach {
		options.encoding = 'UTF-8'
		options.compilerArgs.add('-parameters')
	}

	tasks.withType(Test).configureEach {
		useJUnitPlatform()
	}
}
